GmhOne/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ViewOnRoad/',include('ViewOnRoad.urls')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout', kwargs={'next_page': '/ViewOnRoad'}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ViewOnRoad/urls.py
from django.conf.urls import url
from . import views
from .views import UserCreateView


urlpatterns = [
   url(r'^$',                              views.ViewOnRoad_index,                name='ViewOnRoad_index'),
   url(r'^signup1/$',                      views.ViewOnRoad_signup1,              name='ViewOnRoad_signup1'),
   url(r'^signup2/$',                      views.ViewOnRoad_signup2,              name='ViewOnRoad_signup2'),
   url(r'^signup3/$',                      UserCreateView,                        name='register'),
   url(r'^signup4/$',                      views.ViewOnRoad_signup4,              name='ViewOnRoad_signup4'),
   url(r'^notice/$',                       views.ViewOnRoad_notice,               name='ViewOnRoad_notice'),
   url(r'^fileupload(?P<pk>[1-3])$',       views.ViewOnRoad_fileupload,           name='ViewOnRoad_fileupload'),
   url(r'^storyonroad/$',                  views.ViewOnRoad_storyonroad,          name="ViewOnRoad_storyonroad"),
   url(r'^storyonroad/(?P<pk>\d+)/$',      views.ViewOnRoad_storyonroad_detail,   name="ViewOnRoad_storyonroad_detail"),
   url(r'^longway/$',                      views.ViewOnRoad_longWay,              name='ViewOnRoad_longWay'),
   url(r'^longway/(?P<pk>\d+)/$',          views.ViewOnRoad_longway_detail,       name="ViewOnRoad_longway_detail"),
   url(r'^roadview/$',                     views.ViewOnRoad_roadview,             name="ViewOnRoad_roadview"),
   url(r'^roadview/(?P<pk>\d+)/$',         views.ViewOnRoad_roadview_detail,      name="ViewOnRoad_roadview_detail"),
   url(r'^profile/$',                      views.ViewOnRoad_profile,              name="ViewOnRoad_profile"),
   url(r'^questions/$',                    views.ViewOnRoad_questions,            name="ViewOnRoad_questions"),
   url(r'^questions/(?P<pk>\d+)/$',        views.ViewOnRoad_question_detail,     name="ViewOnRoad_question_detail"),
   url(r'^ask/$',                          views.ViewOnRoad_ask,                  name="ViewOnRoad_ask" ),
   url(r'^storyonroad/last/$',             views.ViewOnRoad_storyonroad_last,                 name="ViewOnRoad_storyonroad_last"),

]
    

ViewOnRoad/models.py
from django.db import models
from django.utils import timezone

class storyonroad_uploadFile_model(models.Model):
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    created_date = models.DateTimeField(default = timezone.now)
    file = models.FileField(upload_to='uploads/',default='settings.MEDIA_ROOT/uploads/GMH_logo.png')
    text = models.TextField()
    MENU_1 = "MYROAD"
    MENU_2 = "RESTAURANT"
    MENU_3 = "HISTORY"
    MENU_4 = "FESTIVAL"
    MENU_5 = "HARDROAD"
    MENU_6 = "ADVENTURE"
    MENU_7 = "REST"
    MENU_CHOICES = (
        (MENU_1,"나의길이야기"),
        (MENU_2,"맛집으로 가는길"),
        (MENU_3,"역사 속으로 가는길"),
        (MENU_4,"축제가는 길"),
        (MENU_5,"고행의 길"),
        (MENU_6,"탐험의 길"),
        (MENU_7,"휴식의 길")
    )
    detail_menu = models.CharField(
        max_length = 10,
        choices = MENU_CHOICES,
        default = MENU_1,
    )
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title


class longway_uploadFile_model(models.Model):
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    created_date = models.DateTimeField(default = timezone.now)
    text = models.TextField()
    file = models.FileField(upload_to='uploads/',default='settings.MEDIA_ROOT/uploads/GMH_logo.png')
    MENU_1 = "ASIA"
    MENU_2 = "CHINA"
    MENU_3 = "TAI"
    MENU_4 = "MIDDEL_EAST"
    MENU_5 = "EUROPE"
    MENU_6 = "AFRICA"
    MENU_7 = "AMERICA"
    MENU_CHOICES = (
        (MENU_1,"아시아"),
        (MENU_2,"중국"),
        (MENU_3,"태국"),
        (MENU_4,"중동"),
        (MENU_5,"유럽"),
        (MENU_6,"아프리카"),
        (MENU_7,"아메리카")
    )
    detail_menu = models.CharField(
        max_length = 10,
        choices = MENU_CHOICES,
        default = MENU_1,
    )
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title


class roadview_uploadFile_model(models.Model):
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    created_date = models.DateTimeField(default = timezone.now)
    file = models.FileField(upload_to='uploads/',default='settings.MEDIA_ROOT/uploads/GMH_logo.png')
    text = models.TextField()
    MENU_1 = "서울"
    MENU_2 = "경기도"
    MENU_3 = "충청도"
    MENU_4 = "전라도"
    MENU_5 = "강원도"
    MENU_6 = "경상도"
    MENU_7 = "제주도"

    MENU_CHOICES = (
        (MENU_1,MENU_1),
        (MENU_2,MENU_2),
        (MENU_3,MENU_3),
        (MENU_4,MENU_4),
        (MENU_5,MENU_5),
        (MENU_6,MENU_6),
        (MENU_7,MENU_7),
    )
    detail_menu = models.CharField(
        max_length = 5,
        choices = MENU_CHOICES,
        default = MENU_1,
    )
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

class question_model(models.Model):
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    created_date = models.DateTimeField(default = timezone.now)
    file = models.FileField(upload_to='uploads/',default = 'settings.MEDIA_ROOT/uploads/GMH_logo.png')
    text = models.TextField()

    def __str__(self):
        return self.title

ViewOnRoad/forms.py
from django import forms
from .models import longway_uploadFile_model
from .models import storyonroad_uploadFile_model,roadview_uploadFile_model
from .models import question_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

class SelectMenuForm(forms.Form):
    MENU_1 = '길위의 이야기'
    MENU_2 = '먼길가기'
    MENU_3 = '거리탐방'

    MENU_CHOICES = (
        (MENU_1,u"길위의 이야기"),
        (MENU_1,u"먼길가기"),
        (MENU_1,u"거리탐방")
    )
    menu = forms.ChoiceField(choices = MENU_CHOICES)

class SelectMenuForm2(forms.Form):
    MENU_1 = '길위의 이야기'
    MENU_2 = '먼길가기'
    MENU_3 = '거리탐방'

    MENU_CHOICES = (
        (MENU_1,u"길위의 이야기"),
        (MENU_1,u"먼길가기"),
        (MENU_1,u"거리탐방")
    )
    menu = forms.ChoiceField(choices = MENU_CHOICES)

class storyonroad_uploadFileForm(forms.ModelForm):
    class Meta:
        model = storyonroad_uploadFile_model
        fields = ['title','file','text','detail_menu']

class longway_UploadFileForm(forms.ModelForm):
    class Meta:
        model = longway_uploadFile_model
        fields = ['title','file','text','detail_menu']

class roadview_uploadFileForm(forms.ModelForm):
    class Meta:
        model = roadview_uploadFile_model
        fields = ['title','file','text','detail_menu']

class question_Form(forms.ModelForm):
    class Meta:
        model = question_model
        fields = ['title','file','text']

class UserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user


class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

ViewOnRoad/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import longway_UploadFileForm,storyonroad_uploadFileForm,roadview_uploadFileForm,question_Form
from .forms import CustomUserCreationForm
from .models import longway_uploadFile_model,storyonroad_uploadFile_model,roadview_uploadFile_model,question_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.

def ViewOnRoad_index(request):
    return render(request,'ViewOnRoad/ViewOnRoad_index.html',{})

def ViewOnRoad_signup1(request):
    return render(request,'ViewOnRoad/Partner/ViewOnRoad_signup1.html',{})

def ViewOnRoad_signup2(request):
    return render(request,'ViewOnRoad/Partner/ViewOnRoad_signup2.html')

def ViewOnRoad_signup4(request):
    if request.user.is_authenticated:
        data = {'ID':request.user.username, '최근 로그인':request.user.last_login}
    else:
        data = {'ID':requset.user, '로그인 여부':request.user.is_authenticated}
    return render(request, 'ViewOnRoad/Partner/ViewOnRoad_signup4.html', context={'data':data})

@login_required
def ViewOnRoad_ask(request):
    if request.method == "POST":
        form = question_Form(request.POST,request.FILES)
        if form.is_valid:
            form = form.save(commit = False)
            form.user = request.user
            form.save()
            return redirect("ViewOnRoad_questions")
    else:
        form = question_Form()
    return render(request,"ViewOnRoad/Partner/ViewOnRoad_ask.html",{
        "form" : form
    })

def ViewOnRoad_questions(request):
    qs = question_model.objects.all()
    qs = qs.order_by("created_date")

    return render(request,'ViewOnRoad/Partner/ViewOnRoad_questions.html',{
        "posts" : qs,
    })

def ViewOnRoad_question_detail(request,pk):
    post = get_object_or_404(question_model,pk=pk)
    return render(request,"ViewOnRoad/Partner/ViewOnRoad_question_detail.html",{
        "file" : post
        })

@login_required
def ViewOnRoad_profile(request):
    if request.user.is_authenticated:
        data = {'ID':request.user.username}
    else:
        data = {'ID':requset.user, '로그인 여부':request.user.is_authenticated}
    return render(request, 'ViewOnRoad/ViewOnRoad_profile.html', context={'data':data})

def ViewOnRoad_notice(request):
    return render(request,'ViewOnRoad/ViewOnRoad_notice.html',{})

@login_required
def ViewOnRoad_fileupload(request,pk):
    if pk == "1":
        if request.method == "POST":
           form = storyonroad_uploadFileForm(request.POST,request.FILES)
           if form.is_valid:
                post = form.save(commit = False)
                post.user = request.user
                post.save()
                return redirect("ViewOnRoad_storyonroad")
        else:
            form = storyonroad_uploadFileForm()
        return render(request,"ViewOnRoad/ViewOnRoad_fileUpload.html",{
            "form":form , "pk":pk
        })
    elif pk == "2":
        if request.method == "POST":
            form = longway_UploadFileForm(request.POST,request.FILES)
            if form.is_valid:
                post = form.save(commit = False)
                post.user = request.user
                post.save()
                return redirect("ViewOnRoad_longWay")
        else:
            form = longway_UploadFileForm()
        return render(request,'ViewOnRoad/ViewOnRoad_fileUpload.html',{
            "form":form , "pk":pk
        })
    elif pk == "3":
        if request.method == "POST":
            form = roadview_uploadFileForm(request.POST,request.FILES)
            if form.is_valid:
                post = form.save(commit = False)
                post.user = request.user
                post.save()
                return redirect("ViewOnRoad_roadview")
        else:
            form = roadview_uploadFileForm() 
        return render(request,"ViewOnRoad/ViewOnRoad_fileUpload.html",{
            "form":form , "pk":pk
        })


def ViewOnRoad_longWay(request):
    qs = longway_uploadFile_model.objects.all()
    order_by_views = longway_uploadFile_model.objects.order_by('-views')
    referenced_video = order_by_views[0]
    qs = qs.order_by('title')
    
    return render(request,'ViewOnRoad/ViewOnRoad_longWay.html',{
        'filelist': qs, "referenced_video" : referenced_video ,
    })

def ViewOnRoad_longway_detail(request,pk):
    qs = get_object_or_404(longway_uploadFile_model,pk=pk)
    qs.views += 1
    qs.save()
    return render(request,'ViewOnRoad/ViewOnRoad_detail.html',{
        "file" : qs, 
    })
def ViewOnRoad_storyonroad(request):
    qs = storyonroad_uploadFile_model.objects.all()
    order_by_views = storyonroad_uploadFile_model.objects.order_by('-views')
    referenced_video = order_by_views[0]
    qs = qs.order_by('title')

    
    return render(request,'ViewOnRoad/ViewOnRoad_storyonroad.html',{
        'filelist': qs, "referenced_video" : referenced_video ,
    })

def ViewOnRoad_storyonroad_detail(request,pk):
    qs = get_object_or_404(storyonroad_uploadFile_model,pk=pk)
    qs.views += 1
    qs.save()
    return render(request,'ViewOnRoad/ViewOnRoad_detail.html',{
        "file" : qs,
    })
def ViewOnRoad_roadview(request):
    qs = roadview_uploadFile_model.objects.all()
    order_by_views = roadview_uploadFile_model.objects.order_by('-views')
    referenced_video = order_by_views[0]
    qs = qs.order_by('title')

    return render(request,'ViewOnRoad/ViewOnRoad_roadview.html',{
        'filelist': qs, "referenced_video" : referenced_video ,
    })


def ViewOnRoad_roadview_detail(request,pk):
    qs = get_object_or_404(roadview_uploadFile_model,pk=pk)
    qs.views +=1
    qs.save()
    return render(request,"ViewOnRoad/ViewOnRoad_detail.html",{
        "file" : qs,
    })
    


def UserCreateView(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            return render(request,'ViewOnRoad/Partner/ViewOnRoad_signup4.html')
 
    else:
        f = CustomUserCreationForm()
 
    return render(request, 'ViewOnRoad/Partner/ViewOnRoad_signup3.html', {'form': f})

def ViewOnRoad_storyonroad_last(request):
    return render(request,'ViewOnRoad/ViewOnRoad_last.html',{})

ViewOnRoad/templates/ViewOnRoad/ViewOnRoad_detail.html
{% extends 'ViewOnRoad/base.html' %}



{% block title%}
<title>{{file.title}}</title>
{% endblock%}

{% block stylelink %}
<style>
    #center{
    position: absolute;
    left: 25%;
    }
    .video{
    text-align : center;
    border : solid 1px;
    width : 600px;
    height : 350px;
    }
    #content{
    width : 600px;
    height : 150px;
    }
    #explain{
    border : solid 1px;
    width : 600px;
    height : 200px;
    }
</style>
{% endblock %}



{% block content %}
    <div id="center">
      <div class = "video">
        <video style="width:600px;height:350px" src = "{{ file.file.url }}" style="width:800px; height:800px" autoplay loop controls>
      </div>
      <br><br>
      <div id="content">
        Title: {{ file.title }}<br><br>
        작성자: {{file.user}}<br><br>
        시간: {{ file.created_date }}<br><br>
      </div>
      <div id="explain">
        {{file.text}}
      </div>
    </div>
{% endblock %}

ViewOnRoad/templates/ViewOnRoad/ViewOnRoad_fileUpload.html
{% extends 'ViewOnRoad/base.html' %}


{% block title%}
<title>파일 업로드</title>
{% endblock%}

{% block stylelink %}
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
<style>
.upload{
    display:block;
    width:65%;
    height:50%;
    margin-left:auto;
    margin-right:auto;
    margin-top:30px;
    text-align:center;
    border:3px solid gray;
    border-radius:7px;
    padding-top : 20px;
    padding-bottom : 20px;
    font-family:'Quicksand', sans-serif;
    font-weight:800;
}

.filebox label , #id_file{
    margin-top:15px;
    display: inline-block;
    padding: .5em .75em;
    color: #fff;
    font-size: inherit;
    line-height: normal;
    vertical-align: middle;
    background-color: #0B0B3B;
    cursor: pointer;
    border: 1px solid gray;
    border-radius: .25em;
    -webkit-transition: background-color 0.2s;
    transition: background-color 0.2s;font-family:'Quicksand', sans-serif;
}

.filebox label:hover ,#id_file:hover{
    background-color: #045FB4;
}

.filebox label:active ,#id_file:active{
    background-color: #585858;
}

.filebox input[type="file"] ,#id_file  {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    border: 0;
}
.upload_label{
    margin-top:0px;
    margin-bottom:-10px;
    font-size : 30px;
    font-family:'Quicksand', sans-serif;
    font-weight:1000;
    color:#2E2E2E;
}

.upload_title{
    border : 1.5px solid gray;
    border-radius : 7px;
    width : 65%;
    display: block;
    margin-top:10px;
    margin-left:auto;
    margin-right:auto;
    padding-top:8px;
    padding-bottom:8px;
    overflow:hidden;
}
#id_title{
    border : 1.5px solid gray;
    border-radius : 7px;
    width : 65%;
    display: block;
    margin-top:10px;
    margin-left:auto;
    margin-right:auto;
    padding-top:8px;
    padding-bottom:8px;
    overflow:hidden;
}

.upload_title{
    border : 1.5px solid gray;
    border-radius : 7px;
    width : 65%;
    display: block;
    margin-top:10px;
    margin-left:auto;
    margin-right:auto;
    margin-bottom:10px;
    padding-top:8px;
    padding-bottom:8px;
    text-align:center;
}

#id_title{
    border : 1.5px solid gray;
    border-radius : 7px;
    width : 65%;
    display: block;
    margin-top:10px;
    margin-left:auto;
    margin-right:auto;
    margin-bottom:10px;
    padding-top:8px;
    padding-bottom:8px;
    text-align:center;
}

.upload_contents{
    border : 1.5px solid gray;
    border-radius : 7px;
    width : 65%;
    height:auto;
    display: block;
    margin-top:10px;
    margin-left:auto;
    margin-right:auto;
    padding-top:8px;
    padding-bottom:8px;
    word-break:break-all;
    text-align:center;
}

#id_text{
    border : 1.5px solid gray;
    border-radius : 7px;
    width : 65%;
    height:auto;
    display: block;
    margin-top:10px;
    margin-left:auto;
    margin-right:auto;
    padding-top:8px;
    padding-bottom:8px;
    word-break:break-all;
    text-align:center;
}

</style>
{% endblock %}

{% block content %}
  <div class = "upload">
    <p class = "upload_label">
        {% if pk == "1" %}
        story on road Viewing
        {% elif pk == "2" %}
        longway Viewing
        {% elif pk == "3" %}
        roadview Viewing
        {% endif %}
    </p>
        <form  method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" class="save btn btn-primary">Save</button>
    </form>
  </div>

{% endblock%}


{% comment %} 
아직 완성 안됨!!
<body>
  <div class = "upload">
    <!--정무의 django 파일 업로드-->
    <p class = "upload_label">
      Viewing
    </p>
    <br>
    <br>

    Title
    <input class = "upload_title" type="text" maxlength = "15">
    Contents
    <textarea  class = "upload_contents" name="fragment" id="code-input" cols="30" rows="10"> </textarea>

    <div class="filebox">
      <label for="ex_file">Upload</label>
    </div>
  </div>
</body>
{% endcomment %}

ViewOnRoad/templates/ViewOnRoad/ViewOnRoad_index.html
{% extends 'ViewOnRoad/base.html' %}

{% block title%}
<title>ViewOnRoad</title>
{% endblock%}

{% block content %}
  <div class = "thumbnail">
    <li>
      <img src="/static/ViewOnRoad/home_1.jpg" alt="">
      <img src="/static/ViewOnRoad/home_2.jpg" alt="">
      <img src="/static/ViewOnRoad/home_3.jpg" alt="">
    </li>
  </div>
{% endblock%}

ViewOnRoad/templates/ViewOnRoad/ViewOnRoad_longWay.html
{% extends 'ViewOnRoad/base.html' %}

{% block title%}
<title>Longway Home</title>
{% endblock%}

{% block stylelink %}
  <style>
.Tmain{
padding : 10px;
}
#FirstGrid{
display: grid;
grid-template-columns : 1fr 3fr;
}
#FirstVideo{
height : 200px;
width : 300px;
border: solid 1px;
margin : 10px;
}
#content{
border: solid 1px;
margin : 10px;
}
.AddButton{
float : right;
border : 0px;
margin : 5px;
}
.SecondGrid{
display: grid;
grid-template-columns : 1fr 1fr 1fr 1fr 1fr;
text-align : center;
margin : 10px;
}
.SecondVideo{
height : 100px;
width : 150px;
border : solid 1px;
margin : 5px;
}
  </style>
{% endblock %}

{% block content %}

  <ul>
      <div class="Tmain">
        <li>추천 VOD</li>
        <br>
        <div id="FirstGrid">
          <div id="FirstVideo">
            <video src = "{{ referenced_video.file.url }}" style="height : 200px ; width : 300px" ></video>
          </div>
          <div id="content">
          </div>
        </div>
      </div>

    <hr>

      <div class="Tmain">
        <li>최근 올라온 길</li>
        <br>
        <form>
          <input class="AddButton"type="button" value="더보기">
        </form>
        <div class="SecondGrid">
          <div class="SecondVideo">
            동영상
          </div>
          <div class="SecondVideo">
            동영상
          </div>
          <div class="SecondVideo">
            동영상
          </div>
          <div class="SecondVideo">
            동영상
          </div>
          <div class="SecondVideo">
            동영상
          </div>
        </div>
      </div>

    <hr>

      <div class="Tmain">
        <li>주제가 있는 길</li>
        <br>
        <ul>
          <li>나의 길이야기</li>
          <form>
            <input class="AddButton"type="button" value="더보기">
          </form>
          <div class="SecondGrid">
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
          </div>

          <li>맛집으로 가는길</li>
          <form>
            <input class="AddButton"type="button" value="더보기">
          </form>
          <div class="SecondGrid">
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
          </div>

          <li>역사속으로 가는길</li>
          <form>
            <input class="AddButton"type="button" value="더보기">
          </form>
          <div class="SecondGrid">
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
            <div class="SecondVideo">
              동영상
            </div>
          </div>
        </ul>
      </div>
    </ul>

<a style = "color : red;" href="{% url 'ViewOnRoad_fileupload' 2 %}">파일 업로드하기</a><br>

{% endblock%}

{% comment %}
  {% for file in filelist %}
    <div class="file">
        <h2><a style = "color : black;" href="{% url 'ViewOnRoad_longway_detail' file.pk %}">{{ file.title }}</a></h2>
        <br>
        <h3>{{ file.file.name }}</h3>
    </div>
{% endcomment %}

ViewOnRoad/templates/ViewOnRoad/ViewOnRoad_notice.html
{% extends 'ViewOnRoad/base.html' %}

{% block stylelink %}
  <link rel="stylesheet" href="/static/ViewOnRoad/alert.css">
{% endblock%}

{% block title%}
<title>회사소개</title>
{% endblock%}

{% block content %}
  <div class = "alert">
    <img src= "/static/ViewOnRoad/road_1.jpg" alt="">
    <img src= "/static/ViewOnRoad/road_2.jpg" alt="">
    <img src= "/static/ViewOnRoad/road_3.jpg" alt="">
  </div>>
{% endblock %}